#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_EMotorcycleTrailMd10011

#include "Basic.hpp"

#include "KawaiiPhysics_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_EMotorcycleTrailMd10011.ABP_EMotorcycleTrailMd10011_C
// 0x0460 (0x0B90 - 0x0730)
class UABP_EMotorcycleTrailMd10011_C final : public UAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0730(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0738(0x0038)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0770(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x0790(0x0020)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup;                  // 0x07B0(0x02A0)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x0A50(0x0138)()

public:
	void ExecuteUbergraph_ABP_EMotorcycleTrailMd10011(int32 EntryPoint);
	void AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_EMotorcycleTrailMd10011_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_EMotorcycleTrailMd10011_C")
	}
	static class UABP_EMotorcycleTrailMd10011_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_EMotorcycleTrailMd10011_C>();
	}
};
DUMPER7_ASSERTS_UABP_EMotorcycleTrailMd10011_C;

}

