#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_BaseRoleNPC

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "ESwim_structs.hpp"
#include "KuroAnim_structs.hpp"
#include "KuroAnim_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "ECharState_structs.hpp"
#include "EMovementDirection_structs.hpp"
#include "ECharParentMoveState_structs.hpp"
#include "ECharViewDirectionState_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_BaseRoleNPC.ABP_BaseRoleNPC_C
// 0xC3C0 (0xCD00 - 0x0940)
class UABP_BaseRoleNPC_C final : public UKuroAnimInstanceChar
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0940(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_5;                              // 0x0948(0x0038)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_7;                   // 0x0980(0x0138)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_6;                   // 0x0AB8(0x0138)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_5;                   // 0x0BF0(0x0138)()
	struct FAnimNode_AdditiveBoneBlend            AnimGraphNode_AdditiveBoneBlend_3;                 // 0x0D28(0x01B8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_4;                              // 0x0EE0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_53;                   // 0x0F18(0x00D8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_3;                              // 0x0FF0(0x0038)()
	uint8                                         Pad_1028[0x8];                                     // 0x1028(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_6;                    // 0x1030(0x01B0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_5;                    // 0x11E0(0x01B0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_4;                    // 0x1390(0x01B0)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_4;                   // 0x1540(0x0138)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_3;                   // 0x1678(0x0138)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_2;                   // 0x17B0(0x0138)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_120;                // 0x18E8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_119;                // 0x1910(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_18;                    // 0x1938(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_76;                      // 0x1968(0x0038)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_4;                   // 0x19A0(0x00C0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_17;                    // 0x1A60(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_16;                    // 0x1A90(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_15;                    // 0x1AC0(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_75;                      // 0x1AF0(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_20;                     // 0x1B28(0x0198)()
	struct FAnimNode_Inertialization              AnimGraphNode_Inertialization;                     // 0x1CC0(0x0070)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_3;                    // 0x1D30(0x01B0)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_1;                   // 0x1EE0(0x0138)()
	uint8                                         Pad_2018[0x8];                                     // 0x2018(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_2;                    // 0x2020(0x01B0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_118;                // 0x21D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_117;                // 0x21F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_116;                // 0x2220(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_115;                // 0x2248(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_114;                // 0x2270(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_113;                // 0x2298(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_112;                // 0x22C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_111;                // 0x22E8(0x0028)()
	struct FAnimNode_AdditiveBoneBlend            AnimGraphNode_AdditiveBoneBlend_2;                 // 0x2310(0x01B8)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_14;                    // 0x24C8(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_13;                    // 0x24F8(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_12;                    // 0x2528(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_74;                      // 0x2558(0x0038)()
	struct FAnimNode_AdditiveBoneBlend            AnimGraphNode_AdditiveBoneBlend_1;                 // 0x2590(0x01B8)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_11;                    // 0x2748(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_10;                    // 0x2778(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_9;                     // 0x27A8(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_73;                      // 0x27D8(0x0038)()
	struct FAnimNode_AdditiveBoneBlend            AnimGraphNode_AdditiveBoneBlend;                   // 0x2810(0x01B8)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_8;                     // 0x29C8(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_7;                     // 0x29F8(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_6;                     // 0x2A28(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_72;                      // 0x2A58(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_110;                // 0x2A90(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_5;                     // 0x2AB8(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_71;                      // 0x2AE8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_19;                     // 0x2B20(0x0198)()
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x2CB8(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_109;                // 0x2CF0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_108;                // 0x2D18(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_107;                // 0x2D40(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_106;                // 0x2D68(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_105;                // 0x2D90(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_52;                   // 0x2DB8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_70;                      // 0x2E90(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_104;                // 0x2EC8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_103;                // 0x2EF0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_102;                // 0x2F18(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_101;                // 0x2F40(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_100;                // 0x2F68(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_99;                 // 0x2F90(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_98;                 // 0x2FB8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_97;                 // 0x2FE0(0x0028)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_3;                  // 0x3008(0x0108)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_69;                      // 0x3110(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_51;                   // 0x3148(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_68;                      // 0x3220(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_18;                     // 0x3258(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_67;                      // 0x33F0(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_96;                 // 0x3428(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_95;                 // 0x3450(0x0028)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_2;                  // 0x3478(0x0108)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_66;                      // 0x3580(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_50;                   // 0x35B8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_65;                      // 0x3690(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_17;                     // 0x36C8(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_64;                      // 0x3860(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_49;                   // 0x3898(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_63;                      // 0x3970(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_94;                 // 0x39A8(0x0028)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_16;                     // 0x39D0(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_62;                      // 0x3B68(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_15;                     // 0x3BA0(0x0198)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x3D38(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_48;                   // 0x3D70(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_61;                      // 0x3E48(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_14;                     // 0x3E80(0x0198)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_5;                              // 0x4018(0x0060)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x4078(0x0038)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_4;                              // 0x40B0(0x0060)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_2;             // 0x4110(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_2;             // 0x4130(0x0020)()
	struct FAnimNode_SightLock                    AnimGraphNode_SightLock;                           // 0x4150(0x01E8)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_2;                   // 0x4338(0x00B0)()
	uint8                                         Pad_43E8[0x8];                                     // 0x43E8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_KuroHumanIK                  AnimGraphNode_KuroHumanIK;                         // 0x43F0(0x02F0)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x46E0(0x0138)()
	struct FAnimNode_CombineCurves                AnimGraphNode_CombineCurves_2;                     // 0x4818(0x0060)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace;            // 0x4878(0x01B8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_47;                   // 0x4A30(0x00D8)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_3;                              // 0x4B08(0x0060)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_2;                              // 0x4B68(0x0060)()
	struct FAnimNode_CombineCurves                AnimGraphNode_CombineCurves_1;                     // 0x4BC8(0x0060)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x4C28(0x0060)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;             // 0x4C88(0x0020)()
	uint8                                         Pad_4CA8[0x8];                                     // 0x4CA8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_RBF                          AnimGraphNode_RBF;                                 // 0x4CB0(0x0150)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;             // 0x4E00(0x0020)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1;                   // 0x4E20(0x00B0)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_3;                     // 0x4ED0(0x00D8)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_1;                  // 0x4FA8(0x0108)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x50B0(0x00C8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_46;                   // 0x5178(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_45;                   // 0x5250(0x00D8)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x5328(0x0108)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_60;                      // 0x5430(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_13;                     // 0x5468(0x0198)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_93;                 // 0x5600(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_92;                 // 0x5628(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_91;                 // 0x5650(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_90;                 // 0x5678(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_89;                 // 0x56A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_88;                 // 0x56C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_87;                 // 0x56F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_86;                 // 0x5718(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_85;                 // 0x5740(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_84;                 // 0x5768(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_83;                 // 0x5790(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_82;                 // 0x57B8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_81;                 // 0x57E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_80;                 // 0x5808(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_79;                 // 0x5830(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_78;                 // 0x5858(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_77;                 // 0x5880(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_76;                 // 0x58A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_75;                 // 0x58D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_74;                 // 0x58F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_73;                 // 0x5920(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_72;                 // 0x5948(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_71;                 // 0x5970(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_70;                 // 0x5998(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_69;                 // 0x59C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_68;                 // 0x59E8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_67;                 // 0x5A10(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_66;                 // 0x5A38(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_65;                 // 0x5A60(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_64;                 // 0x5A88(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_63;                 // 0x5AB0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_62;                 // 0x5AD8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_61;                 // 0x5B00(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_44;                   // 0x5B28(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_59;                      // 0x5C00(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_43;                   // 0x5C38(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_58;                      // 0x5D10(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_60;                 // 0x5D48(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_42;                   // 0x5D70(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_57;                      // 0x5E48(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_59;                 // 0x5E80(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_58;                 // 0x5EA8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_57;                 // 0x5ED0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_56;                 // 0x5EF8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_55;                 // 0x5F20(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_54;                 // 0x5F48(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_53;                 // 0x5F70(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_52;                 // 0x5F98(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_51;                 // 0x5FC0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_50;                 // 0x5FE8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_49;                 // 0x6010(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_48;                 // 0x6038(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_47;                 // 0x6060(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_46;                 // 0x6088(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_45;                 // 0x60B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_44;                 // 0x60D8(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_56;                      // 0x6100(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_55;                      // 0x6138(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_43;                 // 0x6170(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_41;                   // 0x6198(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_54;                      // 0x6270(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_40;                   // 0x62A8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_53;                      // 0x6380(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_39;                   // 0x63B8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_52;                      // 0x6490(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_38;                   // 0x64C8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_51;                      // 0x65A0(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_42;                 // 0x65D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_41;                 // 0x6600(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_37;                   // 0x6628(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_50;                      // 0x6700(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_36;                   // 0x6738(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_49;                      // 0x6810(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_12;                     // 0x6848(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_48;                      // 0x69E0(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_40;                 // 0x6A18(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_47;                      // 0x6A40(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_39;                 // 0x6A78(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_35;                   // 0x6AA0(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_46;                      // 0x6B78(0x0038)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator;                   // 0x6BB0(0x0078)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_45;                      // 0x6C28(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_11;                     // 0x6C60(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_44;                      // 0x6DF8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_34;                   // 0x6E30(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_33;                   // 0x6F08(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_32;                   // 0x6FE0(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_31;                   // 0x70B8(0x00D8)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_2;                     // 0x7190(0x00D8)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_4;                     // 0x7268(0x0030)()
	struct FAnimNode_MultiWayBlend                AnimGraphNode_MultiWayBlend_3;                     // 0x7298(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_43;                      // 0x72E8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_30;                   // 0x7320(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_29;                   // 0x73F8(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_28;                   // 0x74D0(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_27;                   // 0x75A8(0x00D8)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_1;                     // 0x7680(0x00D8)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3;                     // 0x7758(0x0030)()
	struct FAnimNode_MultiWayBlend                AnimGraphNode_MultiWayBlend_2;                     // 0x7788(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_42;                      // 0x77D8(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x7810(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_41;                      // 0x7840(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x7878(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_40;                      // 0x78A8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_10;                     // 0x78E0(0x0198)()
	uint8                                         Pad_7A78[0x8];                                     // 0x7A78(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1;                    // 0x7A80(0x01B0)()
	struct FAnimNode_CombineCurves                AnimGraphNode_CombineCurves;                       // 0x7C30(0x0060)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x7C90(0x0060)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_38;                 // 0x7CF0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_37;                 // 0x7D18(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_36;                 // 0x7D40(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_35;                 // 0x7D68(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_34;                 // 0x7D90(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_33;                 // 0x7DB8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_32;                 // 0x7DE0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_31;                 // 0x7E08(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_30;                 // 0x7E30(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_29;                 // 0x7E58(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_28;                 // 0x7E80(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_27;                 // 0x7EA8(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_39;                      // 0x7ED0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_26;                   // 0x7F08(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_38;                      // 0x7FE0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_25;                   // 0x8018(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_37;                      // 0x80F0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_24;                   // 0x8128(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_36;                      // 0x8200(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_9;                      // 0x8238(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_35;                      // 0x83D0(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_26;                 // 0x8408(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_25;                 // 0x8430(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24;                 // 0x8458(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23;                 // 0x8480(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22;                 // 0x84A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x84D0(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_23;                   // 0x84F8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_34;                      // 0x85D0(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_33;                      // 0x8608(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_32;                      // 0x8640(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_22;                   // 0x8678(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_31;                      // 0x8750(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_21;                   // 0x8788(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_30;                      // 0x8860(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_20;                   // 0x8898(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_29;                      // 0x8970(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_19;                   // 0x89A8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_28;                      // 0x8A80(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_8;                      // 0x8AB8(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_27;                      // 0x8C50(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_18;                   // 0x8C88(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_26;                      // 0x8D60(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_7;                      // 0x8D98(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_25;                      // 0x8F30(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x8F68(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x8F90(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x8FB8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x8FE0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x9008(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x9030(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x9058(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_17;                   // 0x9080(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_24;                      // 0x9158(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_16;                   // 0x9190(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_23;                      // 0x9268(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15;                   // 0x92A0(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_22;                      // 0x9378(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_6;                      // 0x93B0(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_21;                      // 0x9548(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x9580(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_20;                      // 0x9658(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x9690(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_19;                      // 0x9768(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_18;                      // 0x97A0(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_5;                      // 0x97D8(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_17;                      // 0x9970(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x99A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x99D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x99F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x9A20(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x9A48(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x9A70(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x9A98(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_16;                      // 0x9B70(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_15;                      // 0x9BA8(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14;                      // 0x9BE0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x9C18(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x9CF0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x9D28(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x9E00(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x9E38(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x9F10(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x9F48(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_4;                      // 0x9F80(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0xA118(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_3;                      // 0xA150(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0xA2E8(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0xA320(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0xA348(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0xA370(0x0038)()
	uint8                                         Pad_A3A8[0x8];                                     // 0xA3A8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_ExtraFollowAnims             AnimGraphNode_ExtraFollowAnims;                    // 0xA3B0(0x0D60)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0xB110(0x0038)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0xB148(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0xB168(0x0128)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0xB290(0x0020)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive;                       // 0xB2B0(0x00D8)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0xB388(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0xB3B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0xB3D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0xB400(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0xB428(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0xB450(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0xB478(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0xB550(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0xB628(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0xB700(0x00D8)()
	struct FAnimNode_MultiWayBlend                AnimGraphNode_MultiWayBlend_1;                     // 0xB7D8(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0xB828(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0xB860(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0xB938(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0xBA10(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0xBAE8(0x00D8)()
	struct FAnimNode_MultiWayBlend                AnimGraphNode_MultiWayBlend;                       // 0xBBC0(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0xBC10(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0xBC48(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2;                      // 0xBC80(0x0198)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0xBE18(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0xBEF0(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0xBF28(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0xC0C0(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0xC0F8(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0xC128(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0xC160(0x0198)()
	uint8                                         Pad_C2F8[0x8];                                     // 0xC2F8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0xC300(0x01B0)()
	struct FAnimNode_CurveFix                     AnimGraphNode_CurveFix;                            // 0xC4B0(0x0030)()
	struct FAnimNode_KuroCacheBones               AnimGraphNode_KuroCacheBones;                      // 0xC4E0(0x0148)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_3;                   // 0xC628(0x00C0)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_2;                   // 0xC6E8(0x00C0)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_1;                   // 0xC7A8(0x00C0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0xC868(0x00B0)()
	struct FAnimNode_PoseSnapshot                 AnimGraphNode_PoseSnapshot;                        // 0xC918(0x00B0)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer;                     // 0xC9C8(0x00C0)()
	class ATsBaseCharacter_C*                     角色蓝图;                                          // 0xCA88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DeltaTimeX;                                        // 0xCA90(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                速度向量;                                          // 0xCA94(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                加速度;                                            // 0xCAA0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                移动输入向量;                                      // 0xCAAC(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          是否正在移动;                                      // 0xCAB8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          是否有移动输入;                                    // 0xCAB9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CABA[0x2];                                     // 0xCABA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         速度;                                              // 0xCABC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               瞄准旋转;                                          // 0xCAC0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          是否将要移动;                                      // 0xCACC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          正在旋转;                                          // 0xCACD(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CACE[0x2];                                     // 0xCACE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         旋转速度;                                          // 0xCAD0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         旋转混合;                                          // 0xCAD4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVeloctiyBlend                         速度混合;                                          // 0xCAD8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FVector                                相对加速度;                                        // 0xCAE8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLeanAmount                            倾斜量;                                            // 0xCAF4(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	float                                         地上倾斜量平滑速度;                                // 0xCAFC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMovementDirection                            移动方向;                                          // 0xCB00(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CB01[0x3];                                     // 0xCB01(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         站立播放速率;                                      // 0xCB04(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         走跑混合;                                          // 0xCB08(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CB0C[0x4];                                     // 0xCB0C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveFloat*                            站立走步幅混合曲线;                                // 0xCB10(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCurveFloat*                            站立跑步幅混合曲线;                                // 0xCB18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         步幅混合;                                          // 0xCB20(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         动画行走速度;                                      // 0xCB24(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         动画跑步速度;                                      // 0xCB28(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         动画疾跑速度;                                      // 0xCB2C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCurveFloat*                            RelativeSpeedBlendCurve;                           // 0xCB30(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                整体偏移;                                          // 0xCB38(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CB44[0x4];                                     // 0xCB44(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponent*                 角色Mesh;                                          // 0xCB48(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                整体偏移_实际使用_;                                // 0xCB50(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                上一帧模型位置;                                    // 0xCB5C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsAutonomousProxy;                                 // 0xCB68(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CB69[0x3];                                     // 0xCB69(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         瞄准面向;                                          // 0xCB6C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         瞄准仰角;                                          // 0xCB70(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         当前坡度;                                          // 0xCB74(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         视线修正Alpha;                                     // 0xCB78(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                看向位置;                                          // 0xCB7C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CachePercent_LR;                                   // 0xCB88(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CachePercent_FB;                                   // 0xCB8C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                角色向前向量;                                      // 0xCB90(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                外部方向输入;                                      // 0xCB9C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          是否需要原地转身;                                  // 0xCBA8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          右转;                                              // 0xCBA9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_跑停;                                         // 0xCBAA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_跑停_RunStop;                                 // 0xCBAB(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_跑停_SprintStop;                              // 0xCBAC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_跑停_WalkStop;                                // 0xCBAD(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_地面_Sprint;                                  // 0xCBAE(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_地面_Walk;                                    // 0xCBAF(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_地面_Run;                                     // 0xCBB0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_牵手_牵手中;                                  // 0xCBB1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_牵手_被牵手中;                                // 0xCBB2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_牵手_范围内;                                  // 0xCBB3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_牵手_接受邀请中;                              // 0xCBB4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	ECharState                                    CharMoveState;                                     // 0xCBB5(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CBB6[0x2];                                     // 0xCBB6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ExpresionAlpha;                                    // 0xCBB8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RandomEpresionEndTime;                             // 0xCBBC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         眨眼动画时长;                                      // 0xCBC0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         此轮眨眼动画总时长;                                // 0xCBC4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               角色旋转;                                          // 0xCBC8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         原地旋转偏差角;                                    // 0xCBD4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          移动时是否有阻挡;                                  // 0xCBD8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CBD9[0x3];                                     // 0xCBD9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         TimeSeconds;                                       // 0xCBDC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         InSequenceAlpha;                                   // 0xCBE0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash)
	struct FVector                                缓存角色位置;                                      // 0xCBE4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCurveFloat*                            AngelToStepLength;                                 // 0xCBF0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCurveFloat*                            Angle_to_Step_Frequency;                           // 0xCBF8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               综合旋转;                                          // 0xCC00(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FVector                                上一帧位置;                                        // 0xCC0C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         角色位移;                                          // 0xCC18(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          眨眼中;                                            // 0xCC1C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CC1D[0x3];                                     // 0xCC1D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         身高;                                              // 0xCC20(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bComponentStart;                                   // 0xCC24(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	ECharParentMoveState                          CharPositionState;                                 // 0xCC25(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECharViewDirectionState                       CharCameraState;                                   // 0xCC26(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESwim                                         泳态;                                              // 0xCC27(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_ABPLogicParams_C*                   Ts逻辑变量集;                                      // 0xCC28(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          不进行_IK_Lerp;                                    // 0xCC30(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	EKuroHumanIKMode                              IK模式;                                            // 0xCC31(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          使用混合空间;                                      // 0xCC32(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CC33[0x1];                                     // 0xCC33(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              看向角度;                                          // 0xCC34(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CC3C[0x4];                                     // 0xCC3C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector4                               VehicleCollisionMix;                               // 0xCC40(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsVehicleImpact;                                   // 0xCC50(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CC51[0x3];                                     // 0xCC51(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               VehicleSeatRot;                                    // 0xCC54(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         VehicleCollisionAngle;                             // 0xCC60(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         VehicleCollisionStrength;                          // 0xCC64(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         VehicleCollisionAlpha;                             // 0xCC68(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SuddenMoveTrigger;                                 // 0xCC6C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CC6D[0x3];                                     // 0xCC6D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector4                               VehicleSuddenMoveMix;                              // 0xCC70(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CurForwardSpeed;                                   // 0xCC80(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LastForwardSpeed;                                  // 0xCC84(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CurSeatRoll;                                       // 0xCC88(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SuddenMoveCd;                                      // 0xCC8C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SuddenStopTrigger;                                 // 0xCC90(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CC91[0x3];                                     // 0xCC91(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LastSeatRoll;                                      // 0xCC94(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          EnableSwitchPose;                                  // 0xCC98(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CC99[0x7];                                     // 0xCC99(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPoseSnapshot                          CachePose;                                         // 0xCCA0(0x0040)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         SwitchPoseTime;                                    // 0xCCE0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsInPlotBlend;                                     // 0xCCE4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_叠加层_手臂叠加层左手;                        // 0xCCE5(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_叠加层_手臂叠加层右手;                        // 0xCCE6(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_叠加层_下半身通用融合;                        // 0xCCE7(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         站立叠加倾斜量;                                    // 0xCCE8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          是否待机表演;                                      // 0xCCEC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CCED[0x3];                                     // 0xCCED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         待机表演间隔;                                      // 0xCCF0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         当前待机表演计时;                                  // 0xCCF4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          禁用眨眼;                                          // 0xCCF8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_乘坐载具;                                     // 0xCCF9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          状态_地区运动模式;                                 // 0xCCFA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_ABP_BaseRoleNPC(int32 EntryPoint);
	void AnimNotify_LeftLoopSwing();
	void AnimNotify_LeftEndSwing();
	void AnimNotify_LeftStartSwing();
	void AnimNotify_进入坐下待机();
	void AnimNotify_结束坐下();
	void NoExpose();
	void PlotBlendIn();
	void MovementChanged(class ACharacter* Character, EMovementMode PrevMovementMode, uint8 PreviousCustomMode);
	void OnComponentStart();
	void AnimNotify_停止动画();
	void 播放动画(const struct FSDynamicMontageParams& 播放动画_0);
	void BlueprintInitializeAnimation();
	void BlueprintUpdateAnimation(float DeltaTimeX_0);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_35BF23864F2ECEFB8A627AA88F45D9DE();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_62D69E7C4011BA6C967747B0331309B3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_FC5D00D046374EFAE6D4FF8757A2EC55();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_DE70BB2449E575DC49A5BD9387AF8914();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_A08277E44F1E71B8099434BDCD7E22E3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_EB879569483DECB6FA7ECDBC9C8E85C9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_BC40A3A64A41A5541B6E4E9CC2DCD252();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F9F80FF54FEAA113BD02F8B37CEB0812();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_AdditiveBoneBlend_972D5BA748C486E5C3BA5E84EBB7FFCC();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_AdditiveBoneBlend_8708BB834451E3EB4E59C3A2DD8C8D31();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_AdditiveBoneBlend_F499CF534A6986E698D36BA4DB203A54();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_D40DD943485C763F153AF3BA5BAB8DF9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_B6EF5A894136BA7E1B3EDC80AE42D783();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F5F225C54097ECBAB698808B968544C3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_69A8D4C04D59E6FF9F2193AEC85AFDF1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_D7667F094E190371575D33A294CA0593();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_12D5B63A43BEA91A69FF3D9E09D44913();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_71EC0ADC497DCA9F71FA849635BAA6FF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_37283ACE4757CBE458A8DCACAC8384FA();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_54C0791143921BB0C2145DB52A2D1E7D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_2BA72E324A2C3755C78022B557F6A491();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_75CC77F6411E288DF118E4A64360A8A1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_25D5D6714880F255FC261BBF86F6D527();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_5CB65EF244800BD2D7264B96580C906B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_72DFAFBE41537440C4759AB2D3F29556();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_DACFF3464D3F9AB8436B12A8C3BC8B5F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_41429680472D043A4766F2B4A3547DF9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_482074B940ABF6ECD1CD999E796EA34E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3FB54B9D43E2572F934764B89525DBA6();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_697CCA5F461EB64F0A5995B7AB953813();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_15F4BF374115C55BAF6DE084E8329BAD();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_8A9A74574D3EFAD95B682B9762D628A4();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F57C68684C60238886A3D9B21095676D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_9F27C0544AD432DD916ECCAD79037483();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F1EE968D4C35EBE8858ADCA296615B8B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_BB0A26E7433EB47953A74BB9150A949B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_1EBE3AB24D1188D2CA1DD28F1DACFE80();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_0BFF18DF40B3D7DAE87832B09238CB8C();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F811B7054E27C606851206B15100569C();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_BB0F9EE5494DF8709F1B6EAD85AB61B6();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_4C84D2A14F534CE2478E7FA4196612A8();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_946C1FB64468DEB2922F3DB47CA0F108();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3FBACAF34017F5002FD261897498FDB9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F872E4934C5985382E8C969E69266422();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_BEEE3BFE494E3CEB5727B3854D1404D5();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_23664840422729DF8D8A68B2DDD8DBDC();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_34726529440463E15F0244939A7F18B5();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_9EEB9D994327ED66473204A523C67921();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_A4A23A2F45EDAE623B07F3ABD0621315();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_6BBA62AF4C7DD7415CB6AA8A185674E1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_B49A9B634942643B9C81F68BEDE85116();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_302400AC4759384B598B33BC6D6EEB3E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_54372384432A58CEB93EE88069166697();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_450F039C420169024E44EAAF4AE788C8();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_2F16FC824EC60FFD922634B397D4F99F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3203045A42D499B946683D9545476404();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_C8B97CBD41731C7B6E3C6C81CD0C4078();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_7456759B4F157297FDA7CB98916A19A7();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_91B1DB8946BB1ADB7AAD01969592843C();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_8ADD185445C00222746678BD3BD7CAEB();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_78935DD844C357BDD04257A52439863E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_DD513280456121261D6AA19B601191C3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_9B55296240E25E52F5434CA6BFD9193F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_CC2FCFA4422744F114529A914835B6A5();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_E83224AE4CDCB128E3182A994C0D096A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_C9493C78438BBBD610CA87AD5B4AC657();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_1572860A4CBB2FFF06DB6EA8C7AF26B3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_7C4FF4B7436662A2B942DB8E199F221C();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_CEBF3EEB48DDC734B83B0F8D7C582AB8();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_1C6C34AA46A75FA720D8248F4DE31465();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F8058196497AAA5DB641909311715DA6();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_069EFF67460F37CC488676941034E815();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_DA26BB2149B5458E6256DDB8143551A1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_5954DF6E4B9A0F4F9E0523BF3975F430();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_5B3B900E406A6EB56D45A8A150CD5027();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_ModifyBone_C72417F6464CF93BF15FC48FDC7E74B4();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_AdditiveBoneBlend_CD59EF85450C5E805240D0AB9FA6E193();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_KuroHumanIK_36C2723F47E5A6C9D004AD9A68AF8A17();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_CombineCurves_F94882F047B8D7B2DE316584D85149DC();
	bool 是否需要移动();
	void 更新旋转信息();
	void 原地旋转检查();
	void 更新_IK信息();
	void 更新头部转向(const struct FRotator& NewParam);
	void 设置头部转向状态(ESightLockMode SightMode);
	void 更新角色状态();
	void 更新随机表演();
	void 更新移动组件参数();
	void 更新动画组件参数();
	void 更新网络参数();
	void 更新时间参数();
	void 更新上传();
	void 切换地面移动模式时高度补差();
	void 更新状态参数信息();
	void 更新角色信息();
	void 更新移动信息();
	void 绑定组件参数();
	void 组件参数动画蓝图初始化绑定();
	void 初始化身高();
	void 更新载具信息();
	void 更新牵手组件参数();
	void 更新坐下待机计时();
	void 重置坐下待机计时();
	void AnimGraph(const struct FPoseLink& 地区运动状态, struct FPoseLink* AnimGraph_0);
	void 叠加层(struct FPoseLink* 叠加层_0);
	void 手臂叠加层(struct FPoseLink* 手臂叠加层_0);
	void 混合层(const struct FPoseLink& 基础层输入, const struct FPoseLink& 叠加层输入, const struct FPoseLink& 姿势层输入, const struct FPoseLink& 手臂叠加层输入, struct FPoseLink* 混合层_0);
	void 基础姿势层(struct FPoseLink* 基础姿势层_0);
	void 骨骼混合叠加层(const struct FPoseLink& BaseLayer, const struct FPoseLink& OverlayLayer, const struct FPoseLink& BasePose, struct FPoseLink* 骨骼混合叠加层_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_BaseRoleNPC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_BaseRoleNPC_C")
	}
	static class UABP_BaseRoleNPC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_BaseRoleNPC_C>();
	}
};
DUMPER7_ASSERTS_UABP_BaseRoleNPC_C;

}

