#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PD_CharacterControllerData

#include "Basic.hpp"

#include "ECharacterControllerType_structs.hpp"
#include "ECharacterBodySpecifiedType_structs.hpp"
#include "ECharacterMeshPart_structs.hpp"
#include "ECharacterSlotSpecifiedType_structs.hpp"
#include "SMaterialControllerFloatGroup_structs.hpp"
#include "ECharacterControllerApplyType_structs.hpp"
#include "KuroRenderingRuntimeBPPlugin_classes.hpp"
#include "SMaterialControllerLoopTime_structs.hpp"
#include "ECharacterControllerChannelSwitch_structs.hpp"
#include "SMaterialControllerColorGroup_structs.hpp"
#include "ECharacterControllerUVSwitch_structs.hpp"
#include "SMaterialControllerFloatParameter_structs.hpp"
#include "SMaterialControllerColorParameter_structs.hpp"
#include "SMaterialControllerTextureParameter_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass PD_CharacterControllerData.PD_CharacterControllerData_C
// 0x4A40 (0x4CA0 - 0x0260)
class UPD_CharacterControllerData_C final : public UKuroMaterialControllerDataAsset
{
public:
	ECharacterControllerType                      DataType;                                          // 0x0260(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECharacterBodySpecifiedType                   SpecifiedBodyType;                                 // 0x0261(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_262[0x6];                                      // 0x0262(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<ECharacterMeshPart>                    SpecifiedParts;                                    // 0x0268(0x0010)(Edit, BlueprintVisible)
	ECharacterSlotSpecifiedType                   SpecifiedSlotType;                                 // 0x0278(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECharacterControllerApplyType                 MaterialModifyType;                                // 0x0279(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_27A[0x6];                                      // 0x027A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     ReplaceMaterial;                                   // 0x0280(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     ReplaceMaterialMobile;                             // 0x0288(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          RevertMaterial;                                    // 0x0290(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, AdvancedDisplay)
	bool                                          UseRim;                                            // 0x0291(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          UseOutline;                                        // 0x0292(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          OutlineRevertProperty;                             // 0x0293(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, AdvancedDisplay)
	bool                                          UseDissolve;                                       // 0x0294(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_295[0x3];                                      // 0x0295(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSMaterialControllerLoopTime           LoopTime;                                          // 0x0298(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          RimRevertProperty;                                 // 0x02A4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, AdvancedDisplay)
	bool                                          RimUseTex;                                         // 0x02A5(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	ECharacterControllerChannelSwitch             RimChannel;                                        // 0x02A6(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A7[0x1];                                      // 0x02A7(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSMaterialControllerFloatGroup         RimRange;                                          // 0x02A8(0x01B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSMaterialControllerColorGroup         RimColor;                                          // 0x0458(0x0660)(Edit, BlueprintVisible, HasGetValueTypeHash)
	bool                                          OutlineUseTex;                                     // 0x0AB8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_AB9[0x7];                                      // 0x0AB9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSMaterialControllerFloatGroup         OutlineWidth;                                      // 0x0AC0(0x01B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSMaterialControllerColorGroup         OutlineColor;                                      // 0x0C70(0x0660)(Edit, BlueprintVisible, HasGetValueTypeHash)
	bool                                          DissolveRevertProperty;                            // 0x12D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, AdvancedDisplay)
	ECharacterControllerChannelSwitch             DissolveChannel;                                   // 0x12D1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12D2[0x6];                                     // 0x12D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSMaterialControllerFloatGroup         DissolveProgress;                                  // 0x12D8(0x01B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSMaterialControllerColorGroup         DissolveColor;                                     // 0x1488(0x0660)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSMaterialControllerFloatGroup         DissolveColorIntensity;                            // 0x1AE8(0x01B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	bool                                          UseTextureSample;                                  // 0x1C98(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          TextureSampleRevertProperty;                       // 0x1C99(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          UseAlphaToMask;                                    // 0x1C9A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C9B[0x5];                                     // 0x1C9B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             MaskTexture;                                       // 0x1CA0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSMaterialControllerFloatGroup         Rotation;                                          // 0x1CA8(0x01B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	ECharacterControllerUVSwitch::ECharacterControllerUVSwitch UVSelection;                          // 0x1E58(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E59[0x7];                                     // 0x1E59(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSMaterialControllerColorGroup         TextureScaleAndOffset;                             // 0x1E60(0x0660)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSMaterialControllerColorGroup         TextureSpeed;                                      // 0x24C0(0x0660)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSMaterialControllerColorGroup         TextureColorTint;                                  // 0x2B20(0x0660)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSMaterialControllerFloatGroup         OutlineIntensity;                                  // 0x3180(0x01B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	bool                                          UseOuterOutlineEffect;                             // 0x3330(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          UseParameterModify;                                // 0x3331(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3332[0x6];                                     // 0x3332(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSMaterialControllerFloatParameter> FloatParameters;                               // 0x3338(0x0010)(Edit, BlueprintVisible)
	bool                                          UseColor;                                          // 0x3348(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          ColorRevertProperty;                               // 0x3349(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, AdvancedDisplay)
	bool                                          BaseUseTex;                                        // 0x334A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_334B[0x5];                                     // 0x334B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSMaterialControllerColorGroup         BaseColor;                                         // 0x3350(0x0660)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSMaterialControllerFloatGroup         BaseColorIntensity;                                // 0x39B0(0x01B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	bool                                          EmissionUseTex;                                    // 0x3B60(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3B61[0x7];                                     // 0x3B61(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSMaterialControllerColorGroup         EmissionColor;                                     // 0x3B68(0x0660)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	struct FSMaterialControllerFloatGroup         EmissionIntensity;                                 // 0x41C8(0x01B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<struct FSMaterialControllerColorParameter> ColorParameters;                               // 0x4378(0x0010)(Edit, BlueprintVisible)
	bool                                          UseCustomMaterialEffect;                           // 0x4388(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CustomRevertProperty;                              // 0x4389(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, AdvancedDisplay)
	uint8                                         Pad_438A[0x6];                                     // 0x438A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSMaterialControllerFloatParameter> CustomFloatParameters;                         // 0x4390(0x0010)(Edit, BlueprintVisible)
	TArray<struct FSMaterialControllerColorParameter> CustomColorParameters;                         // 0x43A0(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)
	TArray<struct FSMaterialControllerTextureParameter> CustomTextureParameters;                     // 0x43B0(0x0010)(Edit, BlueprintVisible)
	bool                                          UseMotionOffset;                                   // 0x43C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          MotionOffsetRevertProperty;                        // 0x43C1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, AdvancedDisplay)
	uint8                                         Pad_43C2[0x2];                                     // 0x43C2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MotionOffsetLength;                                // 0x43C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MotionAffectVertexRange;                           // 0x43C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_43CC[0x4];                                     // 0x43CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         WeaponCases;                                       // 0x43D0(0x0010)(Edit, BlueprintVisible)
	bool                                          IgnoreTimeDilation;                                // 0x43E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          HiddenAfterEffect;                                 // 0x43E1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_43E2[0x6];                                     // 0x43E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSMaterialControllerFloatGroup         DissolveSmooth;                                    // 0x43E8(0x01B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSMaterialControllerFloatGroup         MotionNoiseSpeed;                                  // 0x4598(0x01B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	bool                                          UseDitherEffect;                                   // 0x4748(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          DitherRevertProperty;                              // 0x4749(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, AdvancedDisplay)
	uint8                                         Pad_474A[0x6];                                     // 0x474A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSMaterialControllerFloatGroup         DitherValue;                                       // 0x4750(0x01B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<class FString>                         OtherCases;                                        // 0x4900(0x0010)(Edit, BlueprintVisible)
	struct FSMaterialControllerFloatGroup         RimIntensity;                                      // 0x4910(0x01B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<class FString>                         CustomPartNames;                                   // 0x4AC0(0x0010)(Edit, BlueprintVisible)
	struct FSMaterialControllerFloatGroup         TextureMaskRange;                                  // 0x4AD0(0x01B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	bool                                          MaskOriginEffect;                                  // 0x4C80(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          UpdateAtLeastOneFrame;                             // 0x4C81(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4C82[0x6];                                     // 0x4C82(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         CustomExcludePartNames;                            // 0x4C88(0x0010)(Edit, BlueprintVisible)
	bool                                          ForceUpdateOnAdd;                                  // 0x4C98(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay)
	bool                                          ForceBattleMask;                                   // 0x4C99(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay)
	bool                                          MobileUseDifferentMaterial;                        // 0x4C9A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, AdvancedDisplay)

public:
	void InitCache();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PD_CharacterControllerData_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PD_CharacterControllerData_C")
	}
	static class UPD_CharacterControllerData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPD_CharacterControllerData_C>();
	}
};
DUMPER7_ASSERTS_UPD_CharacterControllerData_C;

}

